FROM amd64/almalinux:8 as env

ARG AQTINSTALL_VERSION=3.1.6
ARG QT_VERSION=6.4.2
ARG PYTHON_VERSION=3.9

RUN yum -y update \
    && yum -y groupinstall 'Development Tools' \
    && yum -y install \
        wget \
        openssl-devel \
        bzip2-devel \
        libffi-devel \
        cmake \
        clang \
        clang-devel \
        llvm \
        llvm-devel \
        mesa-libGL-devel \
    && dnf --enablerepo=powertools -y install ninja-build \
    && yum clean all \
    && rm -rf /var/cache/yum

#
COPY ./scripts/install_python.sh /
RUN \
    chmod +x /install_python.sh \
    && /install_python.sh \
    && rm -f /install_python.sh
#

#
COPY ./scripts/install_pipx.sh /
RUN \
    chmod +x /install_pipx.sh \
    && /install_pipx.sh \
    && rm -f /install_pipx.sh
#

#
RUN pipx install aqtinstall==${AQTINSTALL_VERSION}
COPY ./scripts/install_qt.sh /
RUN \
    chmod +x /install_qt.sh \
    && /install_qt.sh \
    && rm -f /install_qt.sh
#

ENV PATH="/opt/Qt/${QT_VERSION}/gcc_64/bin:$PATH"

RUN \
    ln -s $(which python3) /usr/local/bin/python \
    && ln -s $(which pip3) /usr/local/bin/pip

RUN python3 -m pip install wheel setuptools

COPY ./scripts/install_extra.sh /
RUN \
    chmod +x /install_extra.sh \
    && /install_extra.sh \
    && rm -f /install_extra.sh

ENV PYSIDE_INSTALL_DIR="/usr/local"

RUN git clone --recurse-submodules https://github.com/python-LimeReport/python-LimeReport \
    && cd python-LimeReport

RUN pip install \
    --extra-index-url=https://python-limereport.github.io/pypi/ \
    --trusted-host python-limereport.github.io \
    shiboken6==${QT_VERSION} pyside6==${QT_VERSION} shiboken6_generator==${QT_VERSION}

RUN \
    export CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) \
    && cd python-LimeReport \
    && python -m pip wheel . --no-deps