FROM quay.io/pypa/manylinux_2_28_x86_64 as env

ARG AQTINSTALL_VERSION=3.1.6
ARG QT_VERSION=6.4.0
ARG PYTHON_VERSION=3.8

ENV PATH="/opt/python/cp38-cp38/bin:$PATH"

RUN yum -y update \
    && yum -y groupinstall 'Development Tools' \
    && yum -y install cmake make ninja-build \
    && yum clean all \
    && rm -rf /var/cache/yum

RUN pipx install aqtinstall==${AQTINSTALL_VERSION} \
    && cd ~ \ 
    && aqt install-qt --outputdir /opt/Qt linux desktop ${QT_VERSION}

ENV PATH="/opt/Qt/${QT_VERSION}/gcc_64/bin:$PATH"

RUN pip install \
    --index-url=https://download.qt.io/official_releases/QtForPython/ \
    --trusted-host download.qt.io \
    shiboken6 pyside6 shiboken6_generator

# RUN cd /opt \
#   && git clone --depth 1 https://github.com/python-LimeReport/python-LimeReport.git \
#   && cd python-LimeReport \
#   && python -m pip wheel . --wheel-dir=/tmp/cibuildwheel/built_wheel --no-deps


# 
# RUN cd /opt \
#    && git clone -b ${QT_VERSION} --single-branch --depth 1 https://code.qt.io/pyside/pyside-setup.git \
#    && cd pyside-setup \
#    && pip install -r requirements.txt \
#    && python setup.py build --qtpaths=/opt/Qt/${QT_VERSION}/gcc_64/bin/qtpaths --parallel $(nproc) bdist_wheel --limited-api yes \
#    && pip install dist/*.whl

# ENV PYSIDE_INSTALL_DIR="/opt/pyside-setup/build/qfpa-py${PYTHON_VERSION}-qt${QT_VERSION}-64bit-release/install"