name: manylinux

on:
  push:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: [self-hosted, Linux, ARM64]
    strategy:
      matrix:
        python: [3.9]
        qt: [6.5.3]
        image: [manylinux_2_31]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.image }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/python-limereport/${{ matrix.image }}:Py-${{ matrix.python }}-Qt-${{ matrix.qt }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            QT_VERSION=${{ matrix.qt }}